// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyRmOMYlzcCXVTZI1gX0rYpzVlcTlbcHg',
    appId: '1:815516989178:web:940c8f6ad2f3f5288ebb43',
    messagingSenderId: '815516989178',
    projectId: 'authtutorial-7b8ba',
    authDomain: 'authtutorial-7b8ba.firebaseapp.com',
    storageBucket: 'authtutorial-7b8ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1gUVTQ1iLSqO94n8C_piFytiGePMldQ',
    appId: '1:815516989178:android:d508966a854cb38c8ebb43',
    messagingSenderId: '815516989178',
    projectId: 'authtutorial-7b8ba',
    storageBucket: 'authtutorial-7b8ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvJlBuDnY9eDNR0VPsdEGPKItYB53lxAQ',
    appId: '1:815516989178:ios:d4d7b372c25dab9d8ebb43',
    messagingSenderId: '815516989178',
    projectId: 'authtutorial-7b8ba',
    storageBucket: 'authtutorial-7b8ba.appspot.com',
    iosBundleId: 'com.example.betterearth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvJlBuDnY9eDNR0VPsdEGPKItYB53lxAQ',
    appId: '1:815516989178:ios:93efbdfeb2777fe28ebb43',
    messagingSenderId: '815516989178',
    projectId: 'authtutorial-7b8ba',
    storageBucket: 'authtutorial-7b8ba.appspot.com',
    iosBundleId: 'com.example.betterearth.RunnerTests',
  );
}
